version: '3'

services:
  mongo:
    restart: always
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - mongodb:/data/db

  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data/db

volumes:
  mongodb:
  redis: